# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZiEZe9JfgbYJs-aVTFWR7m01eaTlv-el
"""
pip install matplotlib

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from babel.numbers import format_currency
sns.set(style='dark')

def create_customer_df(customers_df):
  customer_count = customers_df.groupby(by="customer_city").customer_id.nunique().sort_values(ascending=False)
  customer_count_df = customer_count.reset_index().rename(columns={"customer_id": "customer_count"})
  return customer_count_df

def create_payment_df(orderpayments_df):
  paymenttype_count = orderpayments_df.groupby(by="payment_type").order_id.nunique().sort_values(ascending=False)
  paymenttype_count_df = paymenttype_count.reset_index().rename(columns={"order_id": "paymenttype_count"})
  return paymenttype_count_df

def create_installment_df(orderpayments_df):
  payment_installments_count = orderpayments_df.groupby(by="payment_installments").order_id.nunique().sort_values(ascending=False)
  payment_installments_count_df = payment_installments_count.reset_index().rename(columns={"order_id": "payment_installments_count"})
  return payment_installments_count_df


def create_rating_df(orderreviews_df):
  review_count = orderreviews_df.groupby(by="review_score").order_id.nunique().sort_values(ascending=False) 
  review_count_df = review_count.reset_index().rename(columns={"order_id": "review_count"})
  return review_count_df

all_df = pd.read_csv("all_data.csv")

datetime_columns = ["review_creation_date", "review_answer_timestamp"]
all_df.sort_values(by="review_creation_date", inplace=True)
all_df.reset_index(inplace=True)

for column in datetime_columns:
    all_df[column] = pd.to_datetime(all_df[column])

min_date = all_df["review_creation_date"].min()
max_date = all_df["review_creation_date"].max()

with st.sidebar:
    # Menambahkan logo e-commerce
    st.image("https://github.com/mirama15/E-Commerce/raw/main/ecomerce.png")

    # Mengambil start_date & end_date dari date_input
    start_date, end_date = st.date_input(
        label='Rentang Waktu',min_value=min_date,
        max_value=max_date,
        value=[min_date, max_date]
    )

main_df = all_df[(all_df["review_creation_date"] >= str(start_date)) &
                (all_df["review_creation_date"] <= str(end_date))]

customer_data_df = create_customer_df(main_df)
payment_df = create_payment_df(main_df)
installment_df = create_installment_df(main_df)
review_df = create_rating_df(main_df)

st.header('E-Commerce Brazil Dashboard :sparkles:')

st.subheader('Kota dengan Customer Paling Banyak')
col = st.columns(1)
major_customer = customer_data_df.head(5)
fig, ax = plt.subplots(figsize=(12, 6))
ax.set_facecolor('lightgray')
major_customer.plot(kind='barh', x='customer_city', y='customer_count', color='darkblue', ax=ax)
plt.xlabel('Kota', fontsize=14)
plt.ylabel('Jumlah Customer', fontsize=14)
plt.xticks(rotation=45, ha='right', fontsize=12)
st.pyplot(fig)

st.subheader('Metode Pembayaran Paling Banyak Digunakan Transaksi')
major_paytype = payment_df
fig, ax = plt.subplots(figsize=(12, 6))
ax.set_facecolor('lightgray')
major_paytype.plot(kind='bar', x='payment_type', y='paymenttype_count', color='darkblue', ax=ax)
plt.xlabel('Metode Pembayaran', fontsize=14)
plt.ylabel('Jumlah Customer', fontsize=14)
plt.xticks(rotation=45, ha='right', fontsize=12)
st.pyplot(fig)

st.subheader('Banyak Angsuran Mayoritas Customer Dalam Transaksi Produk')
major_installment = installment_df.head(5)
fig, ax = plt.subplots(figsize=(12, 6))
ax.set_facecolor('lightgray')
major_installment.plot(kind='bar', x='payment_installments', y='payment_installments_count', color='darkblue', ax=ax)
plt.xlabel('Jumlah Angsuran Pembayaran', fontsize=14)
plt.ylabel('Jumlah Customer', fontsize=14)
plt.xticks(rotation=45, ha='right', fontsize=12)
st.pyplot(fig)

st.subheader('Rating Paling Banyak Diberikan Dalam Transaksi Produk')
major_review = review_df.head(5)
fig, ax = plt.subplots(figsize=(12, 6))
ax.set_facecolor('lightgray')
major_review.plot(kind='bar', x='review_score', y='review_count', color='darkblue', ax=ax)
plt.xlabel('Rating', fontsize=14)
plt.ylabel('Jumlah Customer', fontsize=14)
plt.xticks(rotation=45, ha='right', fontsize=12)
st.pyplot(fig)

